template: MaterialSprites.template.java
output: MaterialSprites.java
package: fr.theoszanto.mc.generated
stop-server-after-generation: true
atlases:
  - blocks
  - decorated_pot
  - gui
  - items
  - map_decorations
  - particles
