package com.bluedragonmc.materialsprites.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Loads the platform-independent sprite mapping generated by the Material Sprites Generator plugin.
 * <p>
 * The mapping is keyed by material name (for example {@code acacia_boat} or {@code stone}).
 */
public final class MaterialSpriteData {
	private static final String RESOURCE = "/material-sprites.json";
	private static final Map<String, SpriteSpec> SPRITES = load();

	private MaterialSpriteData() {}

	/** Returns the sprite for a material name, or {@code null} if there is no entry. */
	public static SpriteSpec get(String materialName) {
		return SPRITES.get(materialName);
	}

	/** Returns every material name and its sprite, in the order they were generated. */
	public static Map<String, SpriteSpec> sprites() {
		return SPRITES;
	}

	private static Map<String, SpriteSpec> load() {
		try (InputStream stream = MaterialSpriteData.class.getResourceAsStream(RESOURCE)) {
			if (stream == null)
				throw new IllegalStateException("Missing " + RESOURCE + " on the classpath");
			JsonObject root = JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8))
					.getAsJsonObject();
			Map<String, SpriteSpec> sprites = new LinkedHashMap<>();
			for (Map.Entry<String, JsonElement> entry : root.entrySet()) {
				sprites.put(entry.getKey(), parse(entry.getValue().getAsJsonObject()));
			}
			return Collections.unmodifiableMap(sprites);
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}
	}

	private static SpriteSpec parse(JsonObject json) {
		return switch (json.get("type").getAsString()) {
			case "nothing" -> new SpriteSpec.Nothing();
			case "sprite" -> new SpriteSpec.Sprite(
					json.has("atlas") ? json.get("atlas").getAsString() : null,
					json.get("key").getAsString(),
					json.has("color") ? json.get("color").getAsInt() : null);
			case "head" -> new SpriteSpec.Head(
					json.get("texture").getAsString(),
					!json.has("hat") || json.get("hat").getAsBoolean());
			default -> throw new IllegalStateException("Unknown sprite type: " + json.get("type").getAsString());
		};
	}
}
